// playgrounds/vue/src/components/Radio.vue
<script setup lang="ts">
import type { FieldElementProps } from '@formisch/vue';
import { computed } from 'vue';
import InputErrors from './InputErrors.vue';

interface RadioProps {
  class?: string;
  label?: string;
  value?: string;
  required?: boolean;
  errors: [string, ...string[]] | null;
  props: FieldElementProps;
}

const props = defineProps<RadioProps>();
const model = defineModel<string[] | boolean | undefined>({ required: true });

const checked = computed(() => {
  return model.value === props.value;
});

const handleInput = (event: Event) => {
  const target = event.target as HTMLInputElement;
  model.value = target.value;
};
</script>

<template>
  <div :class="['px-8 lg:px-10', props.class]">
    <label class="flex select-none space-x-4 font-medium md:text-lg lg:text-xl">
      <input
        v-bind="props.props"
        :id="props.props.name"
        class="mt-1 h-4 w-4 cursor-pointer lg:mt-1 lg:h-5 lg:w-5"
        :value="value"
        :checked="checked"
        @input="handleInput"
        :required="required"
        :aria-invalid="!!errors"
        :aria-errormessage="`${props.props.name}-error`"
        type="radio"
      />
      <span>{{ label }}</span>
      <span v-if="required" class="ml-1 text-red-600 dark:text-red-400">*</span>
    </label>
    <InputErrors :name="props.props.name" :errors="errors" />
  </div>
</template>

// playgrounds/preact/src/components/Radio.tsx
import type { FieldElementProps } from '@formisch/preact';
import { ReadonlySignal } from '@preact/signals';
import clsx from 'clsx';
import { forwardRef } from 'preact/compat';
import { InputErrors } from './InputErrors';

interface RadioProps extends FieldElementProps {
  class?: string;
  label?: string;
  value?: string;
  input: ReadonlySignal<boolean | undefined>;
  required?: boolean;
  errors: ReadonlySignal<[string, ...string[]] | null>;
}

/**
 * Radio button that allows users to select an option. The label next to the
 * radio button describes the selection option.
 */
export const Radio = forwardRef<HTMLInputElement, RadioProps>(
  ({ label, value, input, errors, ...props }: RadioProps) => {
    const { name, required } = props;
    return (
      <div class={clsx('px-8 lg:px-10', props.class)}>
        <label class="flex space-x-4 font-medium select-none md:text-lg lg:text-xl">
          <input
            {...props}
            class="mt-1 h-4 w-4 cursor-pointer lg:mt-1 lg:h-5 lg:w-5"
            type="radio"
            id={name}
            value={value}
            checked={input}
            aria-invalid={!!errors?.value}
            aria-errormessage={`${name}-error`}
          />
          <span>{label}</span>{' '}
          {required && (
            <span class="ml-1 text-red-600 dark:text-red-400">*</span>
          )}
        </label>
        <InputErrors name={name} errors={errors} />
      </div>
    );
  }
);
